import Head from 'next/head'
import Image from 'next/image'
import Post from "../component/post";
import Project from "../component/project";

export default function Projects() {
  return (
    <div className='container mx-auto px-4 lg:px-30 xl:px-48'>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p className='my-10 text-6xl font-medium text-gray-800'>Projects</p>
        <Project
          title='Cave aux hirondelles'
          description='Explaining of the greatest project of them all bro ! You wont regret visiting my project'
          img='/images/mountain.jpg'
          date='March 21, 2021'
          link='https://caveauxhirondelles.ch/'
        />
      </div>
    </div>
  )
}
